spring.datasource.url=${DB_URL:jdbc:mysql://mariadb_vehiculos:3306/Sucursal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:vehiculos}
spring.datasource.password=${DB_PASSWORD:Vehiculos1234}
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs